# Generated by Django 4.2.6 on 2023-11-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtional_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Command', models.CharField(max_length=200)),
            ],
        ),
    ]
