# Generated by Django 4.2.6 on 2023-11-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_addtional_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addtional_information',
            new_name='Additional_information',
        ),
    ]
